(() => {
  const CONSENT_KEY='ma_analytics_consent_v1',VISITOR_KEY='ma_apostila_visitor_v1',SESSION_KEY='ma_apostila_session_v1',TIMEOUT=30*60*1000;
  let started=false,session=null,maxScroll=0,pendingSeconds=0,lastInteraction=Date.now();
  function uuid(){try{return crypto.randomUUID();}catch{return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;}}
  function slug(value){return String(value||'acao').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'acao';}
  function visitor(){let id=localStorage.getItem(VISITOR_KEY)||'';if(!id){id=uuid();localStorage.setItem(VISITOR_KEY,id);}return id;}
  function getSession(){const now=Date.now(),query=new URLSearchParams(location.search);let current=null;try{current=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');}catch{}
    if(!current?.id||now-Number(current.lastSeen||0)>TIMEOUT){current={id:uuid(),startedAt:now,lastSeen:now,landingPath:location.pathname||'/',landingQuery:location.search||'',referrer:document.referrer||'',parentSessionId:query.get('hub_session')||''};}
    else{current.lastSeen=now;if(!current.parentSessionId&&query.get('hub_session'))current.parentSessionId=query.get('hub_session');}
    localStorage.setItem(SESSION_KEY,JSON.stringify(current));return current;}
  function device(){const ua=navigator.userAgent||'';if(/iPad|Tablet|PlayBook|Silk/i.test(ua)||(innerWidth>=600&&innerWidth<1024&&navigator.maxTouchPoints>1))return'tablet';if(/Mobi|Android|iPhone|iPod/i.test(ua)||innerWidth<600)return'mobile';return'desktop';}
  function browser(){const ua=navigator.userAgent||'';if(/Instagram/i.test(ua))return'Instagram App';if(/FBAN|FBAV/i.test(ua))return'Facebook App';if(/TikTok/i.test(ua))return'TikTok App';if(/Edg\//.test(ua))return'Edge';if(/OPR\//.test(ua))return'Opera';if(/Chrome\//.test(ua))return'Chrome';if(/Firefox\//.test(ua))return'Firefox';if(/Safari\//.test(ua)&&/Version\//.test(ua))return'Safari';return'Other';}
  function os(){const ua=navigator.userAgent||'';if(/iPhone|iPad|iPod/.test(ua))return'iOS/iPadOS';if(/Android/.test(ua))return'Android';if(/Windows NT/.test(ua))return'Windows';if(/Mac OS X/.test(ua))return'macOS';if(/Linux/.test(ua))return'Linux';return'Other';}
  function acquisition(){const q=new URLSearchParams(session?.landingQuery?.replace(/^\?/,'')||location.search);let source=q.get('utm_source')||'',medium=q.get('utm_medium')||'',ua=navigator.userAgent||'';if(!source&&/Instagram/i.test(ua)){source='Instagram';medium='social';}else if(!source&&/FBAN|FBAV/i.test(ua)){source='Facebook';medium='social';}else if(!source&&/TikTok/i.test(ua)){source='TikTok';medium='social';}return{source,medium,campaign:q.get('utm_campaign')||''};}
  function build(eventName,details={}){session.lastSeen=Date.now();localStorage.setItem(SESSION_KEY,JSON.stringify(session));return{site_id:'apostila_combo',event_id:uuid(),session_id:session.id,visitor_id:visitor(),parent_session_id:session.parentSessionId||'',event_name:eventName,path:location.pathname||'/',landing_path:session.landingPath,landing_query:session.landingQuery,referrer:session.referrer,...acquisition(),device_type:device(),browser:browser(),os:os(),language:navigator.language||'',screen_width:screen?.width||0,screen_height:screen?.height||0,viewport_width:innerWidth||0,viewport_height:innerHeight||0,max_scroll:maxScroll,seconds_before_click:Math.round((Date.now()-session.startedAt)/1000),...details};}
  function track(eventName,details={},beacon=false){if(!started)return;const body=JSON.stringify(build(eventName,details));try{if(beacon&&navigator.sendBeacon)navigator.sendBeacon('/api/track',new Blob([body],{type:'application/json'}));else fetch('/api/track',{method:'POST',headers:{'Content-Type':'application/json'},body,keepalive:true,credentials:'same-origin'}).catch(()=>undefined);}catch{}}
  function section(element){return element.closest('section,header,footer')?.id||element.closest('section,header,footer')?.className?.toString().split(/\s+/)[0]||'geral';}
  function click(event){const anchor=event.target.closest?.('a[href]');if(!anchor||anchor.closest('.ma-consent'))return;const href=anchor.getAttribute('href')||'';if(!href||href.startsWith('#')||href.startsWith('javascript:'))return;const label=(anchor.getAttribute('aria-label')||anchor.querySelector('h3')?.textContent||anchor.textContent||anchor.href).replace(/\s+/g,' ').trim().slice(0,160);track('outbound_click',{link_id:slug(label),link_label:label,target_url:anchor.href,link_position:Array.from(document.querySelectorAll('a[href]')).indexOf(anchor)+1,section:section(anchor)},true);}
  function flush(name='engagement',beacon=false){if(!pendingSeconds&&name==='engagement')return;const value=pendingSeconds;pendingSeconds=0;track(name,{duration_seconds:value,max_scroll:maxScroll},beacon);}
  function start(){if(started)return;started=true;session=getSession();track('page_view');document.addEventListener('click',click,true);addEventListener('scroll',()=>{const total=Math.max(1,document.documentElement.scrollHeight-innerHeight);maxScroll=Math.max(maxScroll,Math.min(100,Math.round(scrollY*100/total)));},{passive:true});['pointerdown','touchstart','keydown'].forEach((name)=>addEventListener(name,()=>{lastInteraction=Date.now();},{passive:true}));setInterval(()=>{if(!document.hidden&&Date.now()-lastInteraction<30000)pendingSeconds+=5;if(pendingSeconds>=15)flush();},5000);addEventListener('pagehide',()=>flush('session_end',true));document.addEventListener('visibilitychange',()=>{if(document.hidden)flush('engagement',true);});}
  function setConsent(value){localStorage.setItem(CONSENT_KEY,value);window.dispatchEvent(new CustomEvent('ma:analytics-consent',{detail:value}));if(value==='granted')start();else if(value==='denied'){started=false;}}
  window.maAnalytics={track,identity:()=>session?{sessionId:session.id,visitorId:visitor(),parentSessionId:session.parentSessionId||'',...acquisition()}: {},consent:()=>localStorage.getItem(CONSENT_KEY)||''};
  if(localStorage.getItem(CONSENT_KEY)!=='denied'){start();}
})();
